worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;
    include /etc/nginx/mime.types;

    server {
        listen 80;

        # Frontend
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # Market Service API
        location /api/market/ {
            proxy_pass http://market_service:8001/api/market/;
        }

        # Market Service WebSocket
        location /ws/price/ {
            proxy_pass http://market_service:8001/ws/price/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        # Alerts Service WebSocket
        location /ws/alerts {
            proxy_pass http://alerts_service:8002/ws/alerts;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}
